export {default as Navb} from './Navb'
export {Footer} from './Footer'
export {Jumbo} from './Jumbo'
export {default as SlideMenu} from './SlideMenu'
export {default as Toaster} from './Toaster'
export {default as Promos} from './Promos'
